### ISSUE TITLE
Args with asterisk is not working when is passed as a last

### ISSUE THREAD

**Issue by felipe-gustavo** [sgmonda/stdio#46] opened 2022-10-27 19:25 UTC
## Description

When pass the parameter that have multiple variable args as last parameter it just return `true` as response for this parameter

Follow the bellow example:

```js
# myfile.js
const args = getopt({
  foo: { args: 1, required: true },
  bar: { args: '*', required: true }
})

console.log(args)
```

When you try to use it with "bar" as last parameter:

```sh
node myfile.js --foo foo --bar bar some-bar
```

You'll get it

```sh
$ node myfile.js --foo foo --bar bar some-bar
{ foo: 'foo', bar: true }
```

But if you try to use "bar" as non-last parameter it'll works:
```sh
node myfile.js --bar bar some-bar --foo foo
# output: { bar: [ 'bar', 'some-bar' ], foo: 'foo' }
```

**Comment by sgmonda** [comment] 2024-01-25 16:40
Sorry for the late reply. This should be fixed in version 2.1.3 as I'm not able to reproduce the issue.
Could you check it?

**Closed by sgmonda** 2024-01-25 16:40 UTC
